## Legislation {#sec-legislation}

### European Union

A cornerstone of the EU’s policy on invasive species is the Invasive Alien Species Regulation, which is concerned with establishing rules “to prevent, minimise and mitigate the adverse effects of invasive alien species on biodiversity and related ecosystem services, and on human health and safety as well as to reduce their social and economic impact” [@noauthor_regulation_2014, p. 2]. It applies to species included in the Invasive Alien Species of Union Concern List (also Union List in short). Being subject to regular updates and extensions [@noauthor_commission_2016; @noauthor_commission_2017; @noauthor_commission_2019; @noauthor_commission_2022; @noauthor_commission_2025], the Union List currently holds 114 plants and animals, among which is the Chinese muntjac.

The Invasive Alien Species Regulation builds on three pillars [@belgian_national_scientific_secretariat_on_invasive_alien_species_belgian_nodate]:

- First, **prevention** requires member states to identify pathways of introduction and take measures to minimize the risk of new IAS entering the EU. It is also prohibited to keep, transport, exchange, release, trade, breed or allow the reproduction of Union List species.
- Second, to ensure **early detection and rapid eradication** member states must establish a monitoring system (termed “surveillance system” in the regulation text^[For a note on terminology, see @adolf_prioritising_2025, pp. 14-15]) to detect emerging IAS as early as possible and respond immediately to eradicate them before they can establish viable populations.
- Third, for established species the regulation obliges member states to determine their distribution and adopt **management measures** of eradication, containment or control to prevent further spread and reduce biodiversity, health, and economic impacts. Both, the species’ distributions and the implemented management actions, more specifically, their effectiveness, fall under the scope of the above mentioned monitoring system.

#### Monitoring targets

The monitoring targets are made more concrete in the regulation’s reporting obligations, at least for the third and partly the second pillar:

A **species’ distribution** should be reported as [@noauthor_commission_2024, pp. 3-4]

- the distribution status in the form of distribution maps (presence and absence per $10\times 10$ km grid cells of the EEA Reference grid [@peifer_about_2011]).

If available, the distribution maps should be complemented by information on the species’

- reproductive status (e.g., does a self-sustaining population exist?),
- reproductive pattern (e.g., sexual vs. asexual),
- introduction (e.g., how was the species predominantly introduced during the reporting period?), and
- spread patterns (e.g., did the species predominantly disperse through natural dispersal?).

The **effectiveness and side effects of early eradication measures** and the **effectiveness and side effects of management measures** should be reported in terms of [@noauthor_commission_2024, pp. 7-8]

- long- or short-term effects on the presence of a species or on numbers of individuals; these effects are to be categorized using a number of pre-defined options (e.g., complete and permanent eradication, partial eradication, no reduction in numbers).
- Side effects are to be reported in terms of the presence of negative effects on the environment, non-targeted species, or human health.

### Flanders

In Flanders, the Decree of the Flemish Government on the Protection and Management of Species [the Species Decree in short; @noauthor_decree_2009] mandates INBO with the coordination of species monitoring, which includes monitoring of IAS. While obligations originating from the European legislation are highlighted, an emphasis is put on determining the species’ distribution as well as changes in abundance, also under management.

It is defined that INBO’s core responsibilities lie in ensuring the quality of data collection, processing and interpretation.
